version: '3.8'

services:
  db:
    image: postgres:15
    container_name: whatsapp-bot-db
    restart: always
    environment:
      POSTGRES_USER: bmafazi
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: chatbot
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: whatsapp-bot-backend
    restart: always
    depends_on:
      - db
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    command: >
      sh -c "npx sequelize-cli db:migrate && npm start"

volumes:
  db_data: